apiVersion: v1
kind: ConfigMap
metadata:
  name: judge0-config
  namespace: default
data:
  REDIS_PASSWORD: "supersecurepassword"
  POSTGRES_DB : "algoearth"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "supersecurepassword"
  POSTGRES_HOST: "postgres.default.svc.cluster.local"
  REDIS_HOST: "redis.default.svc.cluster.local"
