apiVersion: apps/v1
kind: Deployment
metadata:
  name: algoearth
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: algoearth
  template:
    metadata:
      labels:
        app: algoearth
    spec:
      containers:
      - name: main-container
        image: vishal022/algoearth-web:latest
        ports:
          - containerPort: 3000
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: algoearth-web-secret
                key: DATABASE_URL
          - name: NEXTAUTH_SECRET
            valueFrom:
              secretKeyRef:
                name: algoearth-web-secret
                key: NEXTAUTH_SECRET
          - name: REDIS_URL
            valueFrom:
              secretKeyRef:
                name: algoearth-web-secret
                key: REDIS_URL
          - name: JUDGE0_URI
            valueFrom:
              secretKeyRef:
                name: algoearth-web-secret
                key: JUDGE0_URI
          - name: MOUNT_PATH
            valueFrom:
              configMapKeyRef:
                name: algoearth-web-config
                key: MOUNT_PATH
          - name: NEXTAUTH_URL
            valueFrom:
              configMapKeyRef:
                name: algoearth-web-config
                key: NEXTAUTH_URL
        volumeMounts:
          - name: problems
            mountPath: /problems
      volumes:
      - name: problems
        persistentVolumeClaim:
          claimName: problems-pvc 
---