apiVersion: v1
kind: Secret
metadata:
  name: algoearth-web-secret
type: Opaque
data:
  .env: |

# To set up and encode in base64:
# 1. Create a file named '.env' with the following content:
# DATABASE_URL=postgresql://postgres:supersecurepassword@postgres-service.default.svc.cluster.local:5432/algoearth?schema=public
# REDIS_URL=redis://:supersecurepassword@redis-service.default.svc.cluster.local:6379
# MOUNT_PATH=/dev/problems
# NEXTAUTH_URL=https://algoearth.vishalmishra.tech
# NODE_ENV=production
# JUDGE0_URI=http://compiler-service.default.svc.cluster.local:3005
# CLOUD_FLARE_TURNSTILE_SITE_KEY=0x4AAAAAAANypsUam0USvCa
# CLOUD_FLARE_TURNSTILE_SECRET_KEY=0x4AAAAAAANypJbzVgeG1AqnYhENK3hi-o
# NEXTAUTH_SECRET=secret
# JWT_SECRET=secret
#
# 2. Use the following command to encode the file in base64:
#    base64 -w 0 .env > encoded.txt
#
# 3. Copy the content of 'encoded.txt' and paste it as the value for the '.env' key in the Secret resource.
