apiVersion: v1
kind: Secret
metadata:
  name: algoearth-web-secret
type: Opaque
data:
  DATABASE_URL: 
  REDIS_URL: 
  NEXTAUTH_SECRET: 
  JUDGE0_URI: 
  CLOUDFLARE_TURNSTILE_SECRET_KEY: 
  CLOUDFLARE_TURNSTILE_SITE_KEY: 