apiVersion: v1
kind: Service
metadata:
  name: algoearth-web-service
  namespace: default
spec:
  selector:
    app: algoearth
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP