apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: judge0-workers
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: judge0-workers
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
