apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: judge0-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  
  - host: <your url>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: algoearth-web-service
            port:
              number: 3000