apiVersion: apps/v1
kind: Deployment
metadata:
  name: add-problems
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: add-problems
  template:
    metadata:
      labels:
        app: add-problems
    spec:
      initContainers:
      - name: copy-problems
        image: vishal022/algoearth-problems:latest
        command: ['sh', '-c', 'if [ "$(ls -A /dev/problems)" ]; then rm -rf /dev/problems/*; fi && cp -r /usr/src/app/apps/problems/* /dev/problems ']
        volumeMounts:
        - name: problems
          mountPath: /dev/problems 
      containers:
      - name: main-container
        image: busybox
        command: ['sh', '-c', 'sleep infinity']
        volumeMounts:
        - name: problems
          mountPath: /dev/problems
      volumes:
      - name: problems
        persistentVolumeClaim:
          claimName: problems-pvc
---




  