
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: problems-pv
  namespace: default
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  hostPath:
    path: /mnt/data/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: problems-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs

---