apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn
provisioner: driver.longhorn.io
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate 

#    kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml

# helm repo add longhorn https://charts.longhorn.io
# helm repo update


# helm install longhorn longhorn/longhorn --namespace longhorn-system --create-namespace
