apiVersion: apps/v1
kind: Deployment
metadata:
  name: sweeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sweeper
  template:
    metadata:
      labels:
        app: sweeper
    spec:
      containers:
        - name: sweeper
          image: vishal022/algoearth-sweeper:latest
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: algoearth-sweeper-config
                  key: DATABASE_URL