apiVersion: v1
kind: ConfigMap
metadata:
  name: algoearth-c-config
data:
  DATABASE_URL: "postgresql://postgres:supersecurepassword@postgres-service.default.svc.cluster.local:5432/algoearth?schema=public"
  REDIS_URL: "redis://:supersecurepassword@redis-service.default.svc.cluster.local:6379" 