apiVersion: apps/v1
kind: Deployment
metadata:
  name: compiler
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compiler
  template:
    metadata:
      labels:
        app: compiler
    spec:
      containers:
      - name: main-container
        image: vishal022/algoearth-compiler:latest
        ports:
          - containerPort: 3005
        volumeMounts:
        - name: problems
          mountPath: /dev/problems
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: algoearth-compiler-secret
                key: DATABASE_URL
          - name: REDIS_URL
            valueFrom:
              secretKeyRef:
                name: algoearth-compiler-secret
                key: REDIS_URL
      volumes:
      - name: problems
        persistentVolumeClaim:
          claimName: problems-pvc 
---