apiVersion: v1
kind: Service
metadata:
  name: algoearth-compiler-service
  namespace: default
spec:
  selector:
    app: compiler
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005
  type: ClusterIP