apiVersion: v1
kind: ConfigMap
metadata:
  name: judge0-config
  namespace: default
data:
  REDIS_PASSWORD: "vihsalmishra"
  POSTGRES_DB : "judge0"
  POSTGRES_USER: "judge0"
  POSTGRES_PASSWORD: "vihsalmishra"
  POSTGRES_HOST: "postgres.default.svc.cluster.local"
  REDIS_HOST: "redis.default.svc.cluster.local"
  judge0.conf: |
    DB_URL=postgresql://judge0:vishalmishra@10.245.215.213/judge0
    REDIS_URL=redis://:vishalmishra@10.245.190.225:6379/0
    WORKERS=1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: default
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---