name: Build and worker-compiler

on:
  push:
    branches:
      - 'add_inhouse_compiler'
    paths:
      - 'apps/worker-compiler/**'
      - 'docker/worker-compiler/**'
      - '.github/workflows/deploy-worker-compiler.yml' 
  
jobs:
  Deploy-worker-compiler:
    name: Builds and pushes to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3

      - name: Copy Docker image to root
        run: cp ./docker/worker-compiler/Dockerfile . 

      - name: Build Docker Image
        run: docker build --build-arg DATABASE_URL=${{ secrets.TEST_DATABASE_URL }} --build-arg REDIS_URL=${{ secrets.TEST_REDIS_URL }} -t vishal022/algoearth-worker-compiler:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        run: docker push vishal022/algoearth-worker-compiler:latest

      - name: Setup Kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.TEST_KUBE_CONFIG }}
          

      - name: Redeploy the web
        run: kubectl rollout restart deployment/worker-compiler
